name: Auto Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > keystore.jks

      - name: Move Keystore
        run: mkdir -p app/keystore && mv keystore.jks app/keystore/

      - name: Grant permission
        run: chmod +x gradlew

      - name: Build Signed APK
        run: ./gradlew assembleRelease
        env:
          STORE_FILE: app/keystore/keystore.jks
          STORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Upload Release APK
        uses: softprops/action-gh-release@v1
        with:
          files: app/build/outputs/apk/release/*.apk